CREATE SCHEMA IF NOT EXISTS test;
USE test;
CREATE TABLE users (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100),lastName VARCHAR (100),age INT) IF NOT EXISTS users;
INSERT INTO users(name,lastName,age) VALUES